openapi: 3.0.3
info:
  title: Online Movie Renting Website
  description: Welcome to the comprehensive documentation of our website's API, where we proudly present a plethora of endpoints designed to provide an immersive and informative experience for retrieving movies and TV show data. Our API offers an extensive range of features, encompassing essential details such as titles, names, trailer videos, and even recommendations for an enhanced user experience.
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server
paths:
  /auth/verified:
    get:
      tags:
        - auth
      summary: Verify Authentication
      description: Verifies the authentication status of a user
      responses:
        "200":
          description: Authentication verified successfully
        "401":
          description: Unauthorized access
    # Add other HTTP methods and routes here

  /auth/register:
    post:
      tags:
        - auth
      summary: User Registration
      description: Registers a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User's username
                password:
                  type: string
                  description: User's password
      responses:
        "200":
          description: User registered successfully
        "400":
          description: Invalid request payload

  /movie/detail/{movieID}:
    get:
      tags:
        - movie
      summary: Get Movie Details
      description: Retrieves the common movie data like title, overview, ...
      parameters:
        - in: path
          name: movieID
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the movie E.g 502356
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieDetail"
        "404":
          description: Access Denied
        "500":
          description: Internal Server Error

  /movie/recommendations/{movieID}:
    get:
      tags:
        - movie
      summary: Get Movie Recommendations
      description: Retrieves a list of recommended movies based on a given movie id
      parameters:
        - in: path
          name: movieID
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the movie E.g 502356
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recommendations"
        "404":
          description: Access Denied
        "500":
          description: Internal Server Error

  /movie/trailer/{movieID}:
    get:
      tags:
        - movie
      summary: Get Movie Trailer
      description: Retrieves a list of trailer relating to the Movie
      parameters:
        - in: path
          name: movieID
          required: true
          schema:
            type: string
          description: ID of the movie E.g 502356
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trailer"
        "404":
          description: Access Denied
        "500":
          description: Internal Server Error

  /movie/tvDetail/{showID}:
    get:
      tags:
        - tv show
      summary: Get TV show details
      description: Retrieve the Details of a specific TV show like name and overview
      parameters:
        - in: path
          name: showID
          required: true
          schema:
            type: string
          description: ID of the tv show E.g 94605
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Show"
        "404":
          description: Access Denied
        "500":
          description: Internal Server Error
  /movie/showTrailer/{showID}:
    get:
      tags:
        - tv show
      summary: Get the Trailer of the Show
      description: Retrieve a List of TV show's trailer
      parameters:
        - in: path
          name: showID
          required: true
          schema:
            type: string
          description: ID of the tv show E.g 94605
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trailer"
        "404":
          description: Access Denied
        "500":
          description: Internal Server Error
  /movie/tvRecommendations/{showID}:
    get:
      tags:
        - tv show
      summary: Get the show's recommendations
      description: Retrieve a list of recommendations based on the show
      parameters:
        - in: path
          name: showID
          required: true
          schema:
            type: string
          description: ID of the tv show E.g 94605
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recommendations"
        "404":
          description: Access Denied
        "500":
          description: Internal Server Error

  /movie/discovery/{page}:
    get:
      tags:
        - discovery
      summary: Get movie discovery
      description: Retrieve a list of movie that is featured in the discovery sessions
      parameters:
        - in: path
          name: page
          required: true
          schema:
            type: string
          description: ID of the tv show E.g 1
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Discovery"
        "404":
          description: Access Denied
        "500":
          description: Internal Server Error
  /movie/showDiscovery/{page}:
    get:
      tags:
        - discovery
      summary: Get the show discovery
      description: Retrieve the TV shows that are featured in the discovery session
      parameters:
        - in: path
          name: page
          required: true
          schema:
            type: string
          description: ID of the tv show E.g 1
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Discovery"
        "404":
          description: Access Denied
        "500":
          description: Internal Server Error
  /search/?query={query}&page={page}:
    get:
      tags:
        - search
      summary: Get the user's search
      description: Get all the movie or tv show that relating to the the user's search
      parameters:
        - in: path
          name: query
          required: true
          schema:
            type: string
          description: Search for E.g 'Vĩnh'
        - in: path
          name: page
          required: true
          schema:
            type: string
          description: Eg. 1
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Search"
        "404":
          description: Access Denied
        "500":
          description: Internal Server Error
# Add other paths and endpoints here

components:
  schemas:
    Genre:
      type: object
      properties:
        id:
          type: integer
          description: ID of the genre
        name:
          type: string
          description: Name of the genre

    ProductionCompany:
      type: object
      properties:
        id:
          type: integer
          description: ID of the production company
        logo_path:
          type: string
          description: Path to the production company's logo
        name:
          type: string
          description: Name of the production company
        origin_country:
          type: string
          description: Origin country of the production company

    ProductionCountry:
      type: object
      properties:
        iso_3166_1:
          type: string
          description: ISO 3166-1 code of the production country
        name:
          type: string
          description: Name of the production country

    SpokenLanguage:
      type: object
      properties:
        english_name:
          type: string
          description: English name of the spoken language
        iso_639_1:
          type: string
          description: ISO 639-1 code of the spoken language
        name:
          type: string
          description: Name of the spoken language

    MovieDetail:
      type: object
      properties:
        adult:
          type: boolean
          description: Indicates if the movie is suitable for adults
          example: false
        backdrop_path:
          type: string
          description: Path to the backdrop image of the movie
          example: /vinhDepTraiPhoto.jpg
        belongs_to_collection:
          type: object
          nullable: true
          description: Collection details the movie belongs to
          example: null
        budget:
          type: integer
          description: Budget of the movie
          example: 696969420
        genres:
          type: array
          items:
            $ref: "#/components/schemas/Genre"
          description: List of genres of the movie
          example:
            - id: 123
              name: Adventure
        homepage:
          type: string
          description: Official homepage of the movie
          example: https://www.linkedin.com/in/ngoc-vinh-nguyen-22ba95268/
        id:
          type: integer
          description: ID of the movie
          example: 30062002
        imdb_id:
          type: string
          description: IMDb ID of the movie
          example: tt6718170
        original_language:
          type: string
          description: Original language of the movie
          example: en
        original_title:
          type: string
          description: Original title of the movie
          example: The Adventure of Zinh Dragon
        overview:
          type: string
          description: Overview of the movie
          example: A guy named Nguyen Ngoc Vinh wonders why is he so handsome, lol
        popularity:
          type: number
          description: Popularity score of the movie
          example: 69420
        poster_path:
          type: string
          description: Path to the poster image of the movie
          example: /anhVinhDepTrai2.jpg
        production_companies:
          type: array
          items:
            $ref: "#/components/schemas/ProductionCompany"
          description: List of production companies involved in the movie
        production_countries:
          type: array
          items:
            $ref: "#/components/schemas/ProductionCountry"
          description: List of production countries of the movie
          example:
            - iso_3166_1: VN
              name: Vietnam
        release_date:
          type: string
          format: date
          description: Release date of the movie
          example: 2023-04-05
        revenue:
          type: integer
          description: Revenue generated by the movie
          example: 1162684440
        runtime:
          type: integer
          description: Runtime of the movie in minutes
          example: 69420
        spoken_languages:
          type: array
          items:
            $ref: "#/components/schemas/SpokenLanguage"
          description: List of spoken languages in the movie
          example:
            - english_name: English
              iso_639_1: en
              name: English
        status:
          type: string
          example: Released
        tagline:
          type: string
        title:
          type: string
          description: The Title of the Movie
          example: Zinh Da Best
        vote_average:
          type: number
          example: 10
        vote_count:
          type: integer
          example: 1000000

    Recommendations:
      type: object
      properties:
        page:
          type: integer
          example: 1
        results:
          type: array
          items:
            $ref: "#/components/schemas/MovieDetail"
          description: List of movie's recommendations
          example:
            - adult: false
              backdrop_path: /aAgGrfBwna1nO4M2USxwFgK5O0t.jpg
              id: 713704
              title: Evil Dead Rise
              original_language: en
              original_title: Evil Dead Rise
              overview: Three siblings find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.
              poster_path: /5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg
              media_type: movie
              genre_ids:
                - id: 27
                - id: 53
              popularity: 4254.799
              release_date: "2023-04-12"
              vote_average: 7.201
              vote_count: 755

    YoutubeVideo:
      type: object
      properties:
        iso_639_1:
          type: string
          description: ISO 639-1 code of the video
          example: en
        iso_3166_1:
          type: string
          description: ISO 3166-1 code of the video
          example: US
        name:
          type: string
          description: Name of the video
          example: TV Spot 66
        key:
          type: string
          description: Key of the video
          example: LTFGH0rJ-EY
        site:
          type: string
          description: Site where the video is hosted
          example: YouTube
        size:
          type: integer
          description: Size of the video
          example: 1080
        type:
          type: string
          description: Type of the video
          example: Teaser
        official:
          type: boolean
          description: Indicates if the video is official
          example: true
        published_at:
          type: string
          format: date-time
          description: Publish date of the video
          example: "2023-04-10T19:29:54.000Z"
        id:
          type: string
          description: ID of the video
          example: 6439b5ee2938350479a99eb2

    Trailer:
      type: object
      properties:
        page:
          type: integer
          example: 1
        items:
          type: array
          items:
            $ref: "#/components/schemas/YoutubeVideo"
          description: List of movie trailer's youtube id
          example:
            - iso_639_1: en
              iso_3166_1: US
              name: TV Spot 66
              key: LTFGH0rJ-EY
              site: YouTube
              size: 1080
              type: Teaser
              official: true
              published_at: "2023-04-10T19:29:54.000Z"
              id: 6439b5ee2938350479a99eb2

    Creator:
      type: object
      properties:
        id:
          type: integer
        credit_id:
          type: string
        name:
          type: string
        gender:
          type: integer
        profile_path:
          type: string

    Episode:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        overview:
          type: string
        vote_average:
          type: number
        vote_count:
          type: integer
        air_date:
          type: string
        episode_number:
          type: integer
        production_code:
          type: string
        runtime:
          type: integer
        season_number:
          type: integer
        show_id:
          type: integer
        still_path:
          type: string

    Network:
      type: object
      properties:
        id:
          type: integer
        logo_path:
          type: string
        name:
          type: string
        origin_country:
          type: string

    Dates:
      type: object
      properties:
        maximum:
          type: date-time
        minimum:
          type: date-time

    Season:
      type: object
      properties:
        air_date:
          type: string
        episode_count:
          type: integer
        id:
          type: integer
        name:
          type: string
        overview:
          type: string
        poster_path:
          type: string
        season_number:
          type: integer

    Show:
      type: object
      properties:
        adult:
          type: boolean
        backdrop_path:
          type: string
        created_by:
          type: array
          items:
            $ref: "#/components/schemas/Creator"
        episode_run_time:
          type: array
          items:
            type: integer
        first_air_date:
          type: string
        genres:
          type: array
          items:
            $ref: "#/components/schemas/Genre"
        homepage:
          type: string
        id:
          type: integer
        in_production:
          type: boolean
        languages:
          type: array
          items:
            type: string
        last_air_date:
          type: string
        last_episode_to_air:
          $ref: "#/components/schemas/Episode"
        name:
          type: string
        next_episode_to_air:
          $ref: "#/components/schemas/Episode"
        networks:
          type: array
          items:
            $ref: "#/components/schemas/Network"
        number_of_episodes:
          type: integer
        number_of_seasons:
          type: integer
        origin_country:
          type: array
          items:
            type: string
        original_language:
          type: string
        original_name:
          type: string
        overview:
          type: string
        popularity:
          type: number
        poster_path:
          type: string
        production_companies:
          type: array
          items:
            $ref: "#/components/schemas/ProductionCompany"
        production_countries:
          type: array
          items:
            $ref: "#/components/schemas/ProductionCountry"
        seasons:
          type: array
          items:
            $ref: "#/components/schemas/Season"
        spoken_languages:
          type: array
          items:
            $ref: "#/components/schemas/SpokenLanguage"
        status:
          type: string
        tagline:
          type: string
        type:
          type: string
        vote_average:
          type: number
        vote_count:
          type: integer

    Discovery:
      type: array
      items:
        $ref: "#/components/schemas/Recommendations"

    Search:
      type: array
      items:
        $ref: "#/components/schemas/Recommendations"
